# -*- coding: utf-8 -*-
"""data_to_dataframe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ojG8E47tS97JCSWbnWqD97SeL7mK1_8
"""

import os
import pandas as pd
import ast

rootdir = "C:/Users/hp/Desktop/Sproj/Active"  ##Set Root folder directory.

all_dicts = []
all_dicts_normal=[]
for root,dirs,files in os.walk(rootdir):
    new_dict = {}
    dictionary_made = False
    for name in files:
        new_path = os.path.join(root,'stream_details.txt')
        if not os.path.exists(new_path):
            continue
            
        if not dictionary_made:
            with open(new_path) as data:
                temp_dict = ast.literal_eval(data.read())
                for key,values in temp_dict.items():
                    new_key = key.strip()
                    new_dict[new_key]=values
            dictionary_made = True
            
        if name.split('.')[1] == 'txt' or name.split('.')[1] == 'py' or name.split('.')[1]=='exe' or name.split('.')[1]=='ipynb':
            continue
        else:
            file_path = os.path.join(root,name)
            name=name.replace(".mp4",'')
            ad_id = name.split('@')
            if(ad_id[0]=="MainVideo"):
                name_split = name.split("@")
                if len(name_split) == 2:
                    new_dict['Main_Video']["Size"]=os.path.getsize(file_path)
                else:
                    new_dict['Main_Video']['Size'+name_split[-1]]=os.path.getsize(file_path)
            else:
                stripped_key = ad_id[2].strip()
                new_dict[stripped_key]['Size']=os.path.getsize(file_path)
    
    temp_dict={}
    temp_dict[root[-1]]=new_dict
    all_dicts_normal.append(new_dict)
    all_dicts.append(temp_dict)

#Making Rows for DataFrame
all_dicts=all_dicts[1:] #Removing Empty dict at index 0 since it is of the root folder.
all_dicts_normal=all_dicts_normal[1:]
max_number_of_ads = -1
for i in range(len(all_dicts)):
    for key,value in all_dicts[i].items():
        if value["Main_Video"]['UniqueAds']>max_number_of_ads:
            max_number_of_ads=value['Main_Video']['UniqueAds']

column_names = ["Main_Video_Url","Unique_Ads","Total Number of Ads","Duration(s)","Size Original (Bytes)","Size at 240p (Bytes)","Size at 1080p (Bytes)","Avg_Buffer","Resolution"]
add_columns=[]

for i in range(max_number_of_ads):
    ad_id = f"Advertisement {i+1} ID"
    add_columns.append(ad_id)
    ad_count=f"Advertisement {i+1} Count"
    add_columns.append(ad_count)
    ad_skippable = f"Advertisement {i+1} Skippable"
    add_columns.append(ad_skippable)
    skip_duration = f"Advertisement {i+1} Skip Duration"
    add_columns.append(skip_duration)
    resolution = f"Advertisement {i+1} Resolution"
    add_columns.append(resolution)
    size = f"Advertisement {i+1} Size(Bytes)"
    add_columns.append(size)
    duration = f"Advertisement {i+1} Durationn(s)"
    add_columns.append(duration)

new_columns = column_names+add_columns

#Generate the rows
all_data_rows=[]
for i in range(len(all_dicts_normal)):
    row=[]
    main_video_url = all_dicts_normal[i]['Main_Video']['Url']
    row.append(main_video_url)
    unique_ads = all_dicts_normal[i]['Main_Video']['UniqueAds']
    row.append(unique_ads)

    row.append(0) ## For Total Number of ads #Index 2

    duration= all_dicts_normal[i]['Main_Video']['Total Duration']
    row.append(duration)
    size=all_dicts_normal[i]["Main_Video"]["Size"]
    row.append(size)
    size_240p=all_dicts_normal[i]["Main_Video"]["Size240p"]
    row.append(size_240p)
    size_1080p=all_dicts_normal[i]["Main_Video"]["Size1080p"]
    row.append(size_1080p)
    avg= all_dicts_normal[i]['Main_Video']['AvgBuffer']
    row.append(avg)
    res= all_dicts_normal[i]['Main_Video']['Resolution']
    row.append(res)
    total_ads = 0
    for key,value in all_dicts_normal[i].items():
        if key == "Main_Video":
            continue
        else:
            row.append(key)
            row.append(value['Count'])
            total_ads=total_ads+value['Count']
            row.append(value['Skippable'])
            row.append(value['SkipDuration'])
            row.append(value['Resolution'])
            row.append(value['Size'])
            row.append(value['Duration'])
    row[2]=total_ads
    all_data_rows.append(row)

df = pd.DataFrame(all_data_rows,columns=new_columns)

new_columns
## Additions-> Each Video 240p Bytes and 1080p Bytes. 
## Exclude avg_Buffer.
## Buffer Size when ad plays --> Not sure if we can collect right now with accuracy.
## Average of Buffer (Sum/# of values)

df

df.to_csv("Data.csv")